### PR TITLE
Bg header

### PR DESCRIPTION
**Pull request by KarenNgala**
Headbug

### CODE REVIEW

**Comment by GrishonNganga** [comment]
You want to merge the bug to master? Wow good job 😆 😆

**Comment by KarenNgala** [comment]
😂😂Educate me please, for I am but a lowly servant. Where do bugs belong?

**Comment by GrishonNganga** [comment]
😆 Please. I have better jobs to do than to educate lowly servants. So listen and listen closely! 

You are working on your **ft-branch** . When you encounter a branch you cant solve. Create another branch there and then and call it **bg-bug-name** . Once a jedi like thy cometh to your rescue and solves it, you create a PR from **bg-bug-name** to the main **ft-branch** then you continue.

Now off to my masterful duties... 🤣

**Comment by KarenNgala** [comment]
Heading off quietly to the barn

**Pull request merged**
